<?php

declare(strict_types=1);

return [
    'platform_permissions' => [
        ['key' => 'platform.tenants.read', 'name' => 'View tenants'],
        ['key' => 'platform.tenants.manage', 'name' => 'Manage tenants'],
        ['key' => 'platform.support.impersonate', 'name' => 'Support tenant access'],
        ['key' => 'platform.billing.manage', 'name' => 'Manage billing plans'],
        ['key' => 'platform.fleet.operations', 'name' => 'Manage tenant DB fleet'],
        ['key' => 'platform.reports.read', 'name' => 'View platform reports'],
    ],
    'platform_roles' => [
        [
            'key' => 'platform-owner',
            'name' => 'Platform Owner',
            'scope' => 'platform',
            'permissions' => [
                'platform.tenants.read',
                'platform.tenants.manage',
                'platform.support.impersonate',
                'platform.billing.manage',
                'platform.fleet.operations',
                'platform.reports.read',
            ],
        ],
        [
            'key' => 'platform-support',
            'name' => 'Platform Support',
            'scope' => 'platform',
            'permissions' => [
                'platform.tenants.read',
                'platform.support.impersonate',
                'platform.reports.read',
            ],
        ],
        [
            'key' => 'platform-billing',
            'name' => 'Platform Billing',
            'scope' => 'platform',
            'permissions' => [
                'platform.tenants.read',
                'platform.billing.manage',
                'platform.reports.read',
            ],
        ],
    ],
    'tenant_permissions' => [
        'tenant.users.read',
        'tenant.users.manage',
        'tenant.crm.read',
        'tenant.crm.manage',
        'tenant.finance.read',
        'tenant.finance.manage',
        'tenant.analytics.read',
        'tenant.content.manage',
        'tenant.forms.manage',
        'tenant.settings.manage',
    ],
    'tenant_roles' => [
        [
            'key' => 'owner',
            'name' => 'Owner',
            'scope' => 'tenant',
            'permissions' => [
                'tenant.users.read',
                'tenant.users.manage',
                'tenant.crm.read',
                'tenant.crm.manage',
                'tenant.finance.read',
                'tenant.finance.manage',
                'tenant.analytics.read',
                'tenant.content.manage',
                'tenant.forms.manage',
                'tenant.settings.manage',
            ],
        ],
        [
            'key' => 'dispatcher',
            'name' => 'Dispatcher',
            'scope' => 'location',
            'permissions' => [
                'tenant.crm.read',
                'tenant.crm.manage',
                'tenant.forms.manage',
            ],
        ],
        [
            'key' => 'technician-lead',
            'name' => 'Technician Lead',
            'scope' => 'location',
            'permissions' => [
                'tenant.crm.read',
                'tenant.content.manage',
            ],
        ],
        [
            'key' => 'regional-admin',
            'name' => 'Regional Admin',
            'scope' => 'region',
            'permissions' => [
                'tenant.users.read',
                'tenant.crm.read',
                'tenant.crm.manage',
                'tenant.finance.read',
                'tenant.analytics.read',
                'tenant.content.manage',
                'tenant.forms.manage',
            ],
        ],
        [
            'key' => 'location-manager',
            'name' => 'Location Manager',
            'scope' => 'location',
            'permissions' => [
                'tenant.users.read',
                'tenant.crm.read',
                'tenant.crm.manage',
                'tenant.finance.read',
                'tenant.analytics.read',
            ],
        ],
        [
            'key' => 'marketing-manager',
            'name' => 'Marketing Manager',
            'scope' => 'region',
            'permissions' => [
                'tenant.crm.read',
                'tenant.analytics.read',
                'tenant.content.manage',
                'tenant.forms.manage',
            ],
        ],
        [
            'key' => 'enterprise-admin',
            'name' => 'Enterprise Admin',
            'scope' => 'enterprise',
            'permissions' => [
                'tenant.users.read',
                'tenant.users.manage',
                'tenant.crm.read',
                'tenant.crm.manage',
                'tenant.finance.read',
                'tenant.finance.manage',
                'tenant.analytics.read',
                'tenant.content.manage',
                'tenant.forms.manage',
                'tenant.settings.manage',
            ],
        ],
        [
            'key' => 'finance-lead',
            'name' => 'Finance Lead',
            'scope' => 'enterprise',
            'permissions' => [
                'tenant.finance.read',
                'tenant.finance.manage',
                'tenant.analytics.read',
            ],
        ],
        [
            'key' => 'operations-vp',
            'name' => 'Operations VP',
            'scope' => 'enterprise',
            'permissions' => [
                'tenant.users.read',
                'tenant.crm.read',
                'tenant.crm.manage',
                'tenant.analytics.read',
                'tenant.settings.manage',
            ],
        ],
    ],
];
